### ISSUE TITLE
SHA-2 hashes for sign/verify operations

### ISSUE THREAD

**Issue by Kagami** [yann2192/pyelliptic#32]
Hi.
pyelliptic currently [uses SHA-1](https://github.com/yann2192/pyelliptic/blob/master/pyelliptic/ecc.py#L366) to hash messages before signing. I've heard SHA-1 is not considered very secure anymore so what do you think about optional `ecdsa-with-sha256` mode (and maybe -sha512)?

**Comment by Atheros1** [comment]
I think that sha256 would be good although I don't think that sha512 would provide any real value.

**Comment by yann2192** [comment]
Hi,

Sorry for the delay. Yes, I agree, replace SHA1 by SHA256 sounds good. 

@Kagami @Atheros1 https://github.com/yann2192/pyelliptic/pull/33 : It's good for you ?

**Comment by Kagami** [comment]
LGTM, but i think @Atheros1 would prefer to make `ecdsa-with-sha256` mode optional to have some time for upgrade period (PyBitmessage currently uses `ecdsa-with-sha1` and it would be problematic to upgrade all network to new version simultaneously).

**Comment by yann2192** [comment]
Ok, is https://github.com/yann2192/pyelliptic/pull/35 better ?

**Comment by Kagami** [comment]
LGTM, thanks!

**Comment by Atheros1** [comment]
#33 is fine. I like that it uses the secure algorithm by default. PyBitmessage contains a copy of pyelliptic so that it isn't broken by these sorts of changes. I could manually make the changes that are present in #35 and take them out after an upgrade period. My upgrade plan would be for PyBitmessage to verify the signature using both SHA1 and SHA256 and wait for everyone to upgrade. After a while, clients could start generating signatures using SHA256 and then the custom code could be taken out so that it matches pyelliptic. This is what I did for issue #17. I'll just have to be sure that alternative Bitmessage implementations are prepared. 

While we're on it, you might like to switch to EVP_DigestInit_ex. 
Per https://www.openssl.org/docs/crypto/EVP_DigestInit.html : 
"The functions EVP_DigestInit(), EVP_DigestFinal() and EVP_MD_CTX_copy() are obsolete but are retained to maintain compatibility with existing code. New applications should use EVP_DigestInit_ex(), EVP_DigestFinal_ex() and EVP_MD_CTX_copy_ex() because they can efficiently reuse a digest context instead of initializing and cleaning it up on each call and allow non default implementations of digests to be specified.
EVP_DigestInit() behaves in the same way as EVP_DigestInit_ex() except the passed context ctx does not have to be initialized, and it always uses the default digest implementation."

md_ctx is already being initialized with EVP_MD_CTX_init so it appears to me that EVP_DigestInit could be switched to EVP_DigestInit_ex if you want.

**Comment by yann2192** [comment]
Ok, let's go for #33. 

@Atheros1 https://github.com/yann2192/pyelliptic/commit/5d94f8878e2181cd49cd339ed6c593a35e5fc287 seems good for you ?

**Comment by Atheros1** [comment]
Yup, it seems good to me.

**Comment by yann2192** [comment]
Ok, it's in master. I'll push a release on Pypi.
